export let week11 = [
    { num: "1", home: "Seahawks", away: "Cardinals", picked: "none" },
    { num: "2", home: "Ravens", away: "Titans", picked: "none" },
    { num: "3", home: "Panthers", away: "Lions", picked: "none" },
    { num: "4", home: "Browns", away: "Eagles", picked: "none" },
    { num: "5", home: "Texans", away: "Patriots", picked: "none" },
    { num: "6", home: "Colts", away: "Packers", picked: "none" },
    { num: "7", home: "Jaguars", away: "Steelers", picked: "none" },
    { num: "8", home: "Saints", away: "Falcons", picked: "none" },
    { num: "9", home: "Redskins", away: "Bengals", picked: "none" },
    { num: "10", home: "Broncos", away: "Chargers", picked: "none" },
    { num: "11", home: "Vikings", away: "Cowboys", picked: "none" },
    { num: "12", home: "Raiders", away: "Chiefs", picked: "none" },
    { num: "13", home: "Buccaneers", away: "Rams", picked: "none" },
];
