export let weekPS1 = [
    { num: "1", home: "Colts", away: "Eagles", picked: "none" },
    { num: "2", home: "Patriots", away: "Lions", picked: "none" },
    { num: "3", home: "Jets", away: "Giants", picked: "none" },
    { num: "4", home: "Panthers", away: "Jaguars", picked: "none" },
    { num: "5", home: "Seahawks", away: "Raiders", picked: "none" },
    { num: "6", home: "Falcons", away: "Dolphins", picked: "none" },
    { num: "7", home: "Ravens", away: "Bills", picked: "none" },
    { num: "8", home: "Steelers", away: "Buccaneers", picked: "none" },
    { num: "9", home: "Vikings", away: "Texans", picked: "none" },
    { num: "10", home: "Rams", away: "Saints", picked: "none" },
    { num: "11", home: "Packers", away: "Cardinals", picked: "none" },
    { num: "12", home: "Bears", away: "Browns", picked: "none" },
    { num: "13", home: "Redskins", away: "Titans", picked: "none" },
    { num: "14", home: "Chiefs", away: "Bengals", picked: "none" },
    { num: "15", home: "Chargers", away: "Cowboys", picked: "none" },
    { num: "16", home: "Broncos", away: "49ers", picked: "none" },
];
