export let week13 = [
    { num: "1", home: "Ravens", away: "Cowboys", picked: "none" },
    { num: "2", home: "Falcons", away: "Saints", picked: "none" },
    { num: "3", home: "Bears", away: "Lions", picked: "none" },
    { num: "4", home: "Texans", away: "Colts", picked: "none" },
    { num: "5", home: "Dolphins", away: "Bengals", picked: "none" },
    { num: "6", home: "Vikings", away: "Jaguars", picked: "none" },
    { num: "7", home: "Jets", away: "Raiders", picked: "none" },
    { num: "8", home: "Steelers", away: "Redskins", picked: "none" },
    { num: "9", home: "Titans", away: "Browns", picked: "none" },
    { num: "10", home: "Cardinals", away: "Rams", picked: "none" },
    { num: "11", home: "Seahawks", away: "Giants", picked: "none" },
    { num: "12", home: "Packers", away: "Eagles", picked: "none" },
    { num: "13", home: "Chargers", away: "Patriots", picked: "none" },
    { num: "14", home: "Chiefs", away: "Broncos", picked: "none" },
    { num: "15", home: "49ers", away: "Bills", picked: "none" },
];
