export let week12 = [
    { num: "1", home: "Lions", away: "Texans", picked: "none" },
    { num: "2", home: "Cowboys", away: "Redskins", picked: "none" },
    { num: "3", home: "Steelers", away: "Ravens", picked: "none" },
    { num: "4", home: "Falcons", away: "Raiders", picked: "none" },
    { num: "5", home: "Bills", away: "Chargers", picked: "none" },
    { num: "6", home: "Bengals", away: "Giants", picked: "none" },
    { num: "7", home: "Colts", away: "Titans", picked: "none" },
    { num: "8", home: "Jaguars", away: "Browns", picked: "none" },
    { num: "9", home: "Vikings", away: "Panthers", picked: "none" },
    { num: "10", home: "Patriots", away: "Cardinals", picked: "none" },
    { num: "11", home: "Jets", away: "Dolphins", picked: "none" },
    { num: "12", home: "Broncos", away: "Saints", picked: "none" },
    { num: "13", home: "Rams", away: "49ers", picked: "none" },
    { num: "14", home: "Buccaneers", away: "Chiefs", picked: "none" },
    { num: "15", home: "Packers", away: "Bears", picked: "none" },
    { num: "16", home: "Eagles", away: "Seahawks", picked: "none" },
];
