export let week2 = [
    { num: "1", home: "Browns", away: "Bengals", picked: "none" },
    { num: "2", home: "Bears", away: "Giants", picked: "none" },
    { num: "3", home: "Cowboys", away: "Falcons", picked: "none" },
    { num: "4", home: "Packers", away: "Lions", picked: "none" },
    { num: "5", home: "Colts", away: "Vikings", picked: "none" },
    { num: "6", home: "Dolphins", away: "Bills", picked: "none" },
    { num: "7", home: "Jets", away: "49ers", picked: "none" },
    { num: "8", home: "Eagles", away: "Rams", picked: "none" },
    { num: "9", home: "Steelers", away: "Broncos", picked: "none" },
    { num: "10", home: "Buccaneers", away: "Panthers", picked: "none" },
    { num: "11", home: "Titans", away: "Jaguars", picked: "none" },
    { num: "12", home: "Cardinals", away: "Redskins", picked: "none" },
    { num: "13", home: "Texans", away: "Ravens", picked: "none" },
    { num: "14", home: "Chargers", away: "Chiefs", picked: "none" },
    { num: "15", home: "Seahawks", away: "Patriots", picked: "none" },
    { num: "16", home: "Raiders", away: "Saints", picked: "none" },
];
